[2025-10-06T02:30:02.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-06T02:30:02.534+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockPrice_ETL_v3.load_to_snowflake scheduled__2025-10-05T02:30:00+00:00 [queued]>
[2025-10-06T02:30:02.537+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockPrice_ETL_v3.load_to_snowflake scheduled__2025-10-05T02:30:00+00:00 [queued]>
[2025-10-06T02:30:02.537+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-06T02:30:02.541+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_to_snowflake> on 2025-10-05 02:30:00+00:00
[2025-10-06T02:30:02.544+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28385) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-06T02:30:02.544+0000] {standard_task_runner.py:72} INFO - Started process 28388 to run task
[2025-10-06T02:30:02.544+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'StockPrice_ETL_v3', 'load_to_snowflake', 'scheduled__2025-10-05T02:30:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/create_task.py', '--cfg-path', '/tmp/tmp7okc7an9']
[2025-10-06T02:30:02.545+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask load_to_snowflake
[2025-10-06T02:30:02.563+0000] {task_command.py:467} INFO - Running <TaskInstance: StockPrice_ETL_v3.load_to_snowflake scheduled__2025-10-05T02:30:00+00:00 [running]> on host 3e2b30b430ab
[2025-10-06T02:30:02.593+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockPrice_ETL_v3' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T02:30:00+00:00'
[2025-10-06T02:30:02.594+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-06T02:30:02.598+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-06T02:30:02.599+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-06T02:30:02.599+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-06T02:30:02.599+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-06T02:30:03.310+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-06T02:30:03.612+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-06T02:32:00.665+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-06T02:32:00.668+0000] {logging_mixin.py:190} INFO -  Successfully inserted 100 records into Raw.stock_table
[2025-10-06T02:32:00.668+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-06T02:32:00.679+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-06T02:32:00.679+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=StockPrice_ETL_v3, task_id=load_to_snowflake, run_id=scheduled__2025-10-05T02:30:00+00:00, execution_date=20251005T023000, start_date=20251006T023002, end_date=20251006T023200
[2025-10-06T02:32:00.727+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-06T02:32:00.738+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T02:32:00.739+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
